//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_de_Errores.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Defectos
    {
        public int id { get; set; }

        [Required]
        [Display(Name = "FigaaSucursal")]
        public string sucursal { get; set; }
        [Required]
        [Display(Name = "Supervisor")]
        public string supervisor { get; set; }
        [Required]
        [Display(Name = "Categoria de Defecto")]
        public string categoria { get; set; }
        public Nullable<System.DateTime> fechaHora { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.TimeSpan> hora { get; set; }
    }
}
