//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_de_Errores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Defectos
    {
        public int id { get; set; }
        public string sucursal { get; set; }
        public string supervisor { get; set; }
        public string categoria { get; set; }
        public System.DateTime fechaHora { get; set; }
        public System.DateTime fecha { get; set; }
        public System.TimeSpan hora { get; set; }
    }
}
